name: Node.js CI

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run async/await test
        run: node test/async.js

      - name: Run async/await test (debug)
        run: node test/async.js --debug

      - name: Run promise test
        run: node test/promise.js

      - name: Check memory usage
        run: node test/memory.usage.js
